---
title: "R Markdown Presentation Script"
author: "Giulia Grisot"
#date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
---

# Introduction to R Markdown

Hi and welcome to the first part of today's workshop. My name is Giulia and I will introduce you to R Markdown. I will then show you how to create reports, documents and presentations with it.

R Markdown is a tool we use to create *efficient reports*, to *summarize analyses* and *communicate results* to an audience.
With R Markdown, using only R code, you can create several kinds of documents, including HTML and PDFs.
Most importantly, R Markdown ensures that the *results are reproducible*.

Consider the following scenario:

- You've conducted your analyses and created a paper draft where you demonstrate your findings.
- Then you send the paper to a journal and, after a few months, the reviewers request some modifications 
- However, let's imagine that, by then, you have forgotten the exact sequence of steps you went through to get to those first results, or that in the meantime you updated your data files. How are you going to do?

- By generating the results and report directly from code with R Markdown, you *can always reproduce your results, and easily update new data in the workflow*. 

## R Markdown elements

An R Markdown document is made of three components: *metadata*, *text* and, if you need it, *code*.
R Markdown is especially indicated if you are dealing with datasets and plots, but you can also use it as a "zero fuss" alternative to word processors, which you might think of as having a "friendlier" interface, but also often oblige you to waste quite a lot of time on the format adjustments.
With R Markdown, once you define the "rules" you just have to decide how you want to organise the hierarchies within your paper, and the output will come perfectly formatted.

### YAML

At the top of the file, you can see the *YAML header*, containing the file metadata. It is enclosed between two strings of made of three hashes each.
The YAML determined the properties of your markdown output, and depending on your desired format, you can add numerous features to your document, such as weather you want a table of content, whether you want to link the paper to a bib file to add references automatically, and so on.
In this session, we will not focus on the YAML, and we will use a basic syntax that accommodates simple reports. If you want to personalize your YAML more, several tutorials can be found online. I will provide a few links at the end of the session.
One thing that you need to know, however, is that the YAML is sensitive to spaces, tabs and double quotes. Whenever you decide to add some features, pay attention to how these are structured within the YAML.

## Text body

The YAML is followed by the contents that make up your report, the actual body of your document. This can includes both text and code chunks.

## Knit

After we have finished modifying a file, we might want to see it in a more legible form, which can be shared with others. Knitting a file is how we generate an output file from the R markdown file.

When a file is knit, R Markdown transforms the document into the desired output file, reading the text and running the chucks of code.

For example, when the R Markdown file shown on the left is knit, it will create the output shown on the right. We'll learn more about output types later in the chapter.

# Course overview

In this course, we'll have a look at the various elements that make up an R markdown document. Then, we'll learn how to add plots and analyses to a report, organize and improve a report, and customize it bz changing the theme.

## Student performance report

Throughout the course, we'll build a report using an open source dataset of Student Exams Performance from Keggle. This contains 1000 exam score results by students of different genders, from different ethnical groups and whose parents have different level of education.

For instance, we might want to see whether gender, ethnical group and parental education have an effect on how the students perform in several subjects.




To get started, we'll add some code by adding a code chunk. A code chunk is a section that contains the code that will either render output in the report or display the code itself as part of the report. Chunks are what separate the text of the report from the code.

14. Adding code chunks
Code chunks start and end

15. Adding code chunks
with a set of three backticks. The first set of backticks signify the beginning of the code chunk

16. Adding code chunks
and are followed by curly braces that include the letter r, to specify that we are adding r code. Within the curly braces, we can specify a number of other chunk options. We'll be discussing the details of this later in the course.

17. Adding code chunks
In the code chunk shown, we've specified the investment annual summary dataset name in the code chunk. When we knit the file,

18. Adding code chunks
we see the dataset included in the document.

19. Let's practice!

Creating your first R Markdown file

Throughout the course, you'll be working on creating an investment report using two datasets from the World Bank IFC. The first dataset, investment_annual_summary, provides the summary of the dollars in millions provided to each region for each fiscal year, from 2012 to 2018. To get started on your report, you first want to print out the dataset.

To create your report, you'll need to edit the Markdown file shown on the right as described in the instructions, then press the green "Knit HTML" button to knit the file and see the resulting HTML file. We'll discuss other output types later in the course.

In each exercise, the first code chunk in the Markdown file will load the readr package and the datasets you'll be using in the exercise. You'll learn more about the details of this code chunk later in the course, but you won't need to modify it for any of the exercises in this chapter.Creating your first R Markdown file

Throughout the course, you'll be working on creating an investment report using two datasets from the World Bank IFC. The first dataset, investment_annual_summary, provides the summary of the dollars in millions provided to each region for each fiscal year, from 2012 to 2018. To get started on your report, you first want to print out the dataset.

To create your report, you'll need to edit the Markdown file shown on the right as described in the instructions, then press the green "Knit HTML" button to knit the file and see the resulting HTML file. We'll discuss other output types later in the course.

In each exercise, the first code chunk in the Markdown file will load the readr package and the datasets you'll be using in the exercise. You'll learn more about the details of this code chunk later in the course, but you won't need to modify it for any of the exercises in this chapter.



